openapi: 3.0.1
info:
  title: Person API
  description: API for managing persons
  version: 1.0.11
servers:
  - url: http://localhost:8080
paths:
  /api/persons:
    get:
      summary: Retrieve all persons
      responses:
        "200":
          description: A list of persons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PersonResponseRepresentation"
    post:
      summary: Create a new person
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PersonRequestRepresentation"
      responses:
        "200":
          description: The created person
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonResponseRepresentation"
  /api/persons/{id}:
    get:
      summary: Retrieve a specific person by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the person to retrieve
      responses:
        "200":
          description: The requested person
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonResponseRepresentation"
    put:
      summary: Update a specific person
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the person to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PersonRequestRepresentation"
      responses:
        "200":
          description: The updated person
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonResponseRepresentation"
    delete:
      summary: Delete a specific person
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the person to delete
      responses:
        "204":
          description: No Content
components:
  schemas:
    PersonRequestRepresentation:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
          format: int32
    PersonResponseRepresentation:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        age:
          type: integer
          format: int32
